version: "3.8"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pg_test
        ports:
            - '5431:5432'
        volumes:
            - ./pgData:/var/lib/psotgresql/data
    app:
        environment:
            - NODE_ENV=development
        depends_on:
            - "postgres"
        build: .
        ports:
            - "1234:1234"
        env_file: ./.docker.env
        environment: 
            RDS_DB_NAME: postgres
            RDS_PORT: 5431
            RDS_HOSTNAME: postgres
        entrypoint: ["/bin/sh", "./config/entrypoint.sh"]
        volumes:
            - .:/code
            - /code/node_modules
