name: 'Linter'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  lint_test:
    name: 'Linting'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run linter'
        run: npm run lint
